[book]
title = "The Husky Programming Language"
authors = ["Xiyu Zhai"]

[output.html]
additional-css = ["sekiro.css", "theme/2022-edition.css"]
additional-js = ["sekiro.js"]
git-repository-url = "https://github.com/xiyuzhai/husky-book"
